#include "sw/device/lib/runtime/log.h"
#include "hw/ip/rs_encode/rs_encode_sw_smoketest/rs_encode.h"
#include "sw/device/lib/testing/test_framework/ottf_main.h"

#include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"

//定义寄存器
unsigned int *RS_ENCODE_CTRL_SIGNALS_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_CTRL_SIGNALS_REG_OFFSET);

unsigned int *RS_ENCODE_STATE_SIGNALS_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_STATE_SIGNALS_REG_OFFSET);

unsigned int *RS_ENCODE_DATA_IN_0_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_0_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_1_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_1_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_2_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_2_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_3_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_3_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_4_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_4_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_5_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_5_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_6_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_6_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_7_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_7_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_8_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_8_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_9_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_9_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_10_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_10_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_11_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_11_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_12_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_12_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_13_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_13_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_14_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_14_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_15_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_15_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_16_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_16_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_17_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_17_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_18_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_18_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_19_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_19_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_20_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_20_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_21_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_21_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_22_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_22_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_23_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_23_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_24_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_24_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_25_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_25_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_26_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_26_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_27_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_27_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_28_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_28_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_29_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_29_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_30_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_30_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_31_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_31_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_32_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_32_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_33_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_33_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_34_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_34_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_35_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_35_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_36_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_36_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_37_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_37_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_38_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_38_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_39_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_39_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_40_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_40_REG_OFFSET);
unsigned int *RS_ENCODE_DATA_IN_41_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_41_REG_OFFSET);

unsigned int *RS_ENCODE_ENCODED_DATA_OUT_0_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_0_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_1_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_1_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_2_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_2_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_3_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_3_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_4_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_4_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_5_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_5_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_6_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_6_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_7_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_7_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_8_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_8_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_9_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_9_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_10_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_10_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_11_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_11_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_12_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_12_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_13_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_13_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_14_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_14_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_15_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_15_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_16_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_16_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_17_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_17_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_18_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_18_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_19_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_19_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_20_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_20_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_21_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_21_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_22_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_22_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_23_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_23_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_24_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_24_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_25_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_25_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_26_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_26_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_27_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_27_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_28_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_28_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_29_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_29_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_30_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_30_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_31_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_31_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_32_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_32_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_33_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_33_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_34_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_34_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_35_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_35_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_36_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_36_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_37_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_37_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_38_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_38_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_39_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_39_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_40_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_40_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_41_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_41_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_42_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_42_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_43_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_43_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_44_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_44_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_45_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_45_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_46_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_46_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_47_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_47_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_48_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_48_REG_OFFSET);
unsigned int *RS_ENCODE_ENCODED_DATA_OUT_49_REG_ADDR =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_49_REG_OFFSET);


OTTF_DEFINE_TEST_CONFIG();

unsigned int result_buf[50]={0,0,0,0,0,0,0,0,0,0,
                            0,0,0,0,0,0,0,0,0,0,
                            0,0,0,0,0,0,0,0,0,0,
                            0,0,0,0,0,0,0,0,0,0,
                            0,0,0,0,0,0,0,0,0,0};

void rs_encode_function(unsigned int data_input[],unsigned int encoded_output[])
{
    unsigned int *data_in_addr =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_DATA_IN_41_REG_OFFSET);
    unsigned int *data_out_addr =(unsigned int *)(TOP_EARLGREY_RS_ENCODE_BASE_ADDR+RS_ENCODE_ENCODED_DATA_OUT_49_REG_OFFSET);
    unsigned int temp1 = (unsigned int)data_in_addr;
    //LOG_INFO("temp1=%08x",temp1);
    unsigned int temp2 = (unsigned int)data_out_addr;
    //LOG_INFO("temp2=%08x",temp2);

    for (uint8_t i = 0; i < 42; i++)
    {
        data_in_addr =(unsigned int *)temp1;
        *data_in_addr = data_input[i];
        //LOG_INFO("i=%08x",i);
        //LOG_INFO("data_in_addr=%08x",data_in_addr);
        temp1 = (unsigned int)(data_in_addr) - 0x4;//一种操作指针的方法
    }
    /*
    for (uint8_t i = 0; i < 42; i++)
    {
        *data_in_addr = data_input[i];
        //LOG_INFO("i=%08x",i);
        LOG_INFO("data_in_addr=%08x",data_in_addr);
        data_in_addr =(unsigned int *)(RS_ENCODE_DATA_IN_41_REG_ADDR - (i+1) * (0x1u));
    }
    */
    *RS_ENCODE_CTRL_SIGNALS_REG_ADDR |=(1<<RS_ENCODE_CTRL_SIGNALS_ENCODE_EN_BIT);
    asm volatile("" ::: "memory");
    *RS_ENCODE_CTRL_SIGNALS_REG_ADDR &=~(unsigned int)(1<<RS_ENCODE_CTRL_SIGNALS_ENCODE_EN_BIT);
    
    wait_for_RDY_BIT();//等待ready位拉高
    
    for (uint8_t j = 0; j < 50; j++)
    {
        data_out_addr =(unsigned int *)temp2;
        encoded_output[j] = *data_out_addr;
        //LOG_INFO("j=%08x",j);
        //LOG_INFO("data_out_addr=%08x",data_out_addr);
        temp2 = (unsigned int)(data_out_addr) - 0x4;
    }
    /*
    for (uint8_t j = 0; j < 50; j++)
    {
        encoded_output[j] = *data_out_addr;
        //LOG_INFO("j=%08x",j);
        LOG_INFO("data_out_addr=%08x",data_out_addr);
        data_out_addr =(unsigned int *)(RS_ENCODE_ENCODED_DATA_OUT_49_REG_ADDR - (j+1) * (0x1u));//将output_data移到数组中
    }
    */
}

uint8_t checkBit(unsigned int* registerAddress, unsigned int bit) {  
    return (*registerAddress & (1 << bit)) != 0;  
}

//等待rdy
void wait_for_RDY_BIT(void)
{ 
  while (!checkBit(RS_ENCODE_STATE_SIGNALS_REG_ADDR,RS_ENCODE_STATE_SIGNALS_READY_BIT_BIT))//应该问red!!!
  {
    asm volatile("" ::: "memory");
  }
    
}


bool test_main(void) {

    LOG_INFO("Now, rs_encode unit test!");
    LOG_INFO("Load data,expected encoded result:d9dcbd68(HEAD)");
    rs_encode_function(data_in_buf,result_buf);
    LOG_INFO("Actual result");
    LOG_INFO("%08x",result_buf[0] );
    return true;
}
