// Generated register defines for rs_encode

#ifndef _RS_ENCODE_REG_DEFS_
#define _RS_ENCODE_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif

static unsigned int data_in_buf[42]={0xa8a7a6a5,0xa4a3a2a1,0xa09f9e9d,0x9c9b9a99,0x98979695,0x94939291,0x908f8e8d,0x8c8b8a89,0x88878685,0x84838281,0x807f7e7d,0x7c7b7a79,0x78777675,0x74737271,0x706f6e6d,0x6c6b6a69,0x68676665,0x64636261,0x605f5e5d,0x5c5b5a59,0x58575655,0x54535251,0x504f4e4d,0x4c4b4a49,0x48474645,0x44434241,0x403f3e3d,0x3c3b3a39,0x38373635,0x34333231,0x302f2e2d,0x2c2b2a29,0x28272625,0x24232221,0x201f1e1d,0x1c1b1a19,0x18171615,0x14131211,0x100f0e0d,0x0c0b0a09,0x08070605,0x04030201};

//static unsigned int data_in_buf[42]={};

//声明函数
void rs_encode_function(unsigned int data_input[],unsigned int encoded_output[]);

uint8_t checkBit(unsigned int* registerAddress, unsigned int bit);

void wait_for_RDY_BIT(void);
// Number registers for input data
#define RS_ENCODE_PARAM_NUMREGS_DATA_IN 42

// Number registers for output data
#define RS_ENCODE_PARAM_NUMREGS_ENCODED_DATA 50

// Register width
#define RS_ENCODE_PARAM_REG_WIDTH 32

// Control
#define RS_ENCODE_CTRL_SIGNALS_REG_OFFSET 0x0
#define RS_ENCODE_CTRL_SIGNALS_REG_RESVAL 0x2u
#define RS_ENCODE_CTRL_SIGNALS_ENCODE_EN_BIT 0
#define RS_ENCODE_CTRL_SIGNALS_CLRN_BIT 1

// The rs_encode states
#define RS_ENCODE_STATE_SIGNALS_REG_OFFSET 0x4
#define RS_ENCODE_STATE_SIGNALS_REG_RESVAL 0x0u
#define RS_ENCODE_STATE_SIGNALS_VALID_BIT_BIT 0
#define RS_ENCODE_STATE_SIGNALS_READY_BIT_BIT 1

// data input (common parameters)
#define RS_ENCODE_DATA_IN_DATA_IN_FIELD_WIDTH 32
#define RS_ENCODE_DATA_IN_MULTIREG_COUNT 42

// data input
#define RS_ENCODE_DATA_IN_0_REG_OFFSET 0x8
#define RS_ENCODE_DATA_IN_0_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_1_REG_OFFSET 0xc
#define RS_ENCODE_DATA_IN_1_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_2_REG_OFFSET 0x10
#define RS_ENCODE_DATA_IN_2_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_3_REG_OFFSET 0x14
#define RS_ENCODE_DATA_IN_3_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_4_REG_OFFSET 0x18
#define RS_ENCODE_DATA_IN_4_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_5_REG_OFFSET 0x1c
#define RS_ENCODE_DATA_IN_5_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_6_REG_OFFSET 0x20
#define RS_ENCODE_DATA_IN_6_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_7_REG_OFFSET 0x24
#define RS_ENCODE_DATA_IN_7_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_8_REG_OFFSET 0x28
#define RS_ENCODE_DATA_IN_8_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_9_REG_OFFSET 0x2c
#define RS_ENCODE_DATA_IN_9_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_10_REG_OFFSET 0x30
#define RS_ENCODE_DATA_IN_10_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_11_REG_OFFSET 0x34
#define RS_ENCODE_DATA_IN_11_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_12_REG_OFFSET 0x38
#define RS_ENCODE_DATA_IN_12_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_13_REG_OFFSET 0x3c
#define RS_ENCODE_DATA_IN_13_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_14_REG_OFFSET 0x40
#define RS_ENCODE_DATA_IN_14_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_15_REG_OFFSET 0x44
#define RS_ENCODE_DATA_IN_15_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_16_REG_OFFSET 0x48
#define RS_ENCODE_DATA_IN_16_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_17_REG_OFFSET 0x4c
#define RS_ENCODE_DATA_IN_17_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_18_REG_OFFSET 0x50
#define RS_ENCODE_DATA_IN_18_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_19_REG_OFFSET 0x54
#define RS_ENCODE_DATA_IN_19_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_20_REG_OFFSET 0x58
#define RS_ENCODE_DATA_IN_20_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_21_REG_OFFSET 0x5c
#define RS_ENCODE_DATA_IN_21_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_22_REG_OFFSET 0x60
#define RS_ENCODE_DATA_IN_22_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_23_REG_OFFSET 0x64
#define RS_ENCODE_DATA_IN_23_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_24_REG_OFFSET 0x68
#define RS_ENCODE_DATA_IN_24_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_25_REG_OFFSET 0x6c
#define RS_ENCODE_DATA_IN_25_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_26_REG_OFFSET 0x70
#define RS_ENCODE_DATA_IN_26_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_27_REG_OFFSET 0x74
#define RS_ENCODE_DATA_IN_27_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_28_REG_OFFSET 0x78
#define RS_ENCODE_DATA_IN_28_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_29_REG_OFFSET 0x7c
#define RS_ENCODE_DATA_IN_29_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_30_REG_OFFSET 0x80
#define RS_ENCODE_DATA_IN_30_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_31_REG_OFFSET 0x84
#define RS_ENCODE_DATA_IN_31_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_32_REG_OFFSET 0x88
#define RS_ENCODE_DATA_IN_32_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_33_REG_OFFSET 0x8c
#define RS_ENCODE_DATA_IN_33_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_34_REG_OFFSET 0x90
#define RS_ENCODE_DATA_IN_34_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_35_REG_OFFSET 0x94
#define RS_ENCODE_DATA_IN_35_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_36_REG_OFFSET 0x98
#define RS_ENCODE_DATA_IN_36_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_37_REG_OFFSET 0x9c
#define RS_ENCODE_DATA_IN_37_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_38_REG_OFFSET 0xa0
#define RS_ENCODE_DATA_IN_38_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_39_REG_OFFSET 0xa4
#define RS_ENCODE_DATA_IN_39_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_40_REG_OFFSET 0xa8
#define RS_ENCODE_DATA_IN_40_REG_RESVAL 0x0u

// data input
#define RS_ENCODE_DATA_IN_41_REG_OFFSET 0xac
#define RS_ENCODE_DATA_IN_41_REG_RESVAL 0x0u

// result output (common parameters)
#define RS_ENCODE_ENCODED_DATA_OUT_ENCODED_OUT_FIELD_WIDTH 32
#define RS_ENCODE_ENCODED_DATA_OUT_MULTIREG_COUNT 50

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_0_REG_OFFSET 0xb0
#define RS_ENCODE_ENCODED_DATA_OUT_0_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_1_REG_OFFSET 0xb4
#define RS_ENCODE_ENCODED_DATA_OUT_1_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_2_REG_OFFSET 0xb8
#define RS_ENCODE_ENCODED_DATA_OUT_2_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_3_REG_OFFSET 0xbc
#define RS_ENCODE_ENCODED_DATA_OUT_3_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_4_REG_OFFSET 0xc0
#define RS_ENCODE_ENCODED_DATA_OUT_4_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_5_REG_OFFSET 0xc4
#define RS_ENCODE_ENCODED_DATA_OUT_5_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_6_REG_OFFSET 0xc8
#define RS_ENCODE_ENCODED_DATA_OUT_6_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_7_REG_OFFSET 0xcc
#define RS_ENCODE_ENCODED_DATA_OUT_7_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_8_REG_OFFSET 0xd0
#define RS_ENCODE_ENCODED_DATA_OUT_8_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_9_REG_OFFSET 0xd4
#define RS_ENCODE_ENCODED_DATA_OUT_9_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_10_REG_OFFSET 0xd8
#define RS_ENCODE_ENCODED_DATA_OUT_10_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_11_REG_OFFSET 0xdc
#define RS_ENCODE_ENCODED_DATA_OUT_11_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_12_REG_OFFSET 0xe0
#define RS_ENCODE_ENCODED_DATA_OUT_12_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_13_REG_OFFSET 0xe4
#define RS_ENCODE_ENCODED_DATA_OUT_13_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_14_REG_OFFSET 0xe8
#define RS_ENCODE_ENCODED_DATA_OUT_14_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_15_REG_OFFSET 0xec
#define RS_ENCODE_ENCODED_DATA_OUT_15_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_16_REG_OFFSET 0xf0
#define RS_ENCODE_ENCODED_DATA_OUT_16_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_17_REG_OFFSET 0xf4
#define RS_ENCODE_ENCODED_DATA_OUT_17_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_18_REG_OFFSET 0xf8
#define RS_ENCODE_ENCODED_DATA_OUT_18_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_19_REG_OFFSET 0xfc
#define RS_ENCODE_ENCODED_DATA_OUT_19_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_20_REG_OFFSET 0x100
#define RS_ENCODE_ENCODED_DATA_OUT_20_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_21_REG_OFFSET 0x104
#define RS_ENCODE_ENCODED_DATA_OUT_21_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_22_REG_OFFSET 0x108
#define RS_ENCODE_ENCODED_DATA_OUT_22_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_23_REG_OFFSET 0x10c
#define RS_ENCODE_ENCODED_DATA_OUT_23_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_24_REG_OFFSET 0x110
#define RS_ENCODE_ENCODED_DATA_OUT_24_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_25_REG_OFFSET 0x114
#define RS_ENCODE_ENCODED_DATA_OUT_25_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_26_REG_OFFSET 0x118
#define RS_ENCODE_ENCODED_DATA_OUT_26_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_27_REG_OFFSET 0x11c
#define RS_ENCODE_ENCODED_DATA_OUT_27_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_28_REG_OFFSET 0x120
#define RS_ENCODE_ENCODED_DATA_OUT_28_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_29_REG_OFFSET 0x124
#define RS_ENCODE_ENCODED_DATA_OUT_29_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_30_REG_OFFSET 0x128
#define RS_ENCODE_ENCODED_DATA_OUT_30_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_31_REG_OFFSET 0x12c
#define RS_ENCODE_ENCODED_DATA_OUT_31_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_32_REG_OFFSET 0x130
#define RS_ENCODE_ENCODED_DATA_OUT_32_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_33_REG_OFFSET 0x134
#define RS_ENCODE_ENCODED_DATA_OUT_33_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_34_REG_OFFSET 0x138
#define RS_ENCODE_ENCODED_DATA_OUT_34_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_35_REG_OFFSET 0x13c
#define RS_ENCODE_ENCODED_DATA_OUT_35_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_36_REG_OFFSET 0x140
#define RS_ENCODE_ENCODED_DATA_OUT_36_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_37_REG_OFFSET 0x144
#define RS_ENCODE_ENCODED_DATA_OUT_37_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_38_REG_OFFSET 0x148
#define RS_ENCODE_ENCODED_DATA_OUT_38_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_39_REG_OFFSET 0x14c
#define RS_ENCODE_ENCODED_DATA_OUT_39_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_40_REG_OFFSET 0x150
#define RS_ENCODE_ENCODED_DATA_OUT_40_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_41_REG_OFFSET 0x154
#define RS_ENCODE_ENCODED_DATA_OUT_41_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_42_REG_OFFSET 0x158
#define RS_ENCODE_ENCODED_DATA_OUT_42_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_43_REG_OFFSET 0x15c
#define RS_ENCODE_ENCODED_DATA_OUT_43_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_44_REG_OFFSET 0x160
#define RS_ENCODE_ENCODED_DATA_OUT_44_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_45_REG_OFFSET 0x164
#define RS_ENCODE_ENCODED_DATA_OUT_45_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_46_REG_OFFSET 0x168
#define RS_ENCODE_ENCODED_DATA_OUT_46_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_47_REG_OFFSET 0x16c
#define RS_ENCODE_ENCODED_DATA_OUT_47_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_48_REG_OFFSET 0x170
#define RS_ENCODE_ENCODED_DATA_OUT_48_REG_RESVAL 0x0u

// result output
#define RS_ENCODE_ENCODED_DATA_OUT_49_REG_OFFSET 0x174
#define RS_ENCODE_ENCODED_DATA_OUT_49_REG_RESVAL 0x0u

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _RS_ENCODE_REG_DEFS_
// End generated register defines for rs_encode