// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rom_ctrl__rom", '{
        '{32'h00008000, 32'h0000fffe}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h411e0000, 32'h411e007e}
    }},
    '{"hmac", '{
        '{32'h41110000, 32'h41111ffe}
    }},
    '{"kmac", '{
        '{32'h41120000, 32'h41120ffe}
    }},
    '{"aes", '{
        '{32'h41100000, 32'h411000fe}
    }},
    '{"entropy_src", '{
        '{32'h41160000, 32'h411600fe}
    }},
    '{"csrng", '{
        '{32'h41150000, 32'h4115007e}
    }},
    '{"edn0", '{
        '{32'h41170000, 32'h4117007e}
    }},
    '{"otbn", '{
        '{32'h41130000, 32'h4113fffe}
    }},
    '{"keymgr", '{
        '{32'h41140000, 32'h411400fe}
    }},
    '{"sm3", '{
        '{32'h411a0000, 32'h411a003e}
    }},
    '{"sm4", '{
        '{32'h411b0000, 32'h411b003e}
    }},
    '{"rs_encode", '{
        '{32'h42110000, 32'h421101fe}
    }},
    '{"rs_decode", '{
        '{32'h42120000, 32'h421201fe}
    }},
    '{"puf1", '{
        '{32'h42130000, 32'h4213003e}
    }},
    '{"puf2", '{
        '{32'h42140000, 32'h4214003e}
    }},
    '{"puf_reg", '{
        '{32'h42150000, 32'h4215003e}
    }},
    '{"pcr", '{
        '{32'h42160000, 32'h4216003e}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rot", 0, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "aes",
        "entropy_src",
        "csrng",
        "edn0",
        "hmac",
        "otbn",
        "keymgr",
        "kmac",
        "sm3",
        "sm4",
        "rs_encode",
        "rs_decode",
        "puf1",
        "puf2",
        "puf_reg",
        "pcr"}}
};
